/**
 * Centralized schema exports for form validation
 */

// Project schemas
export {
  createProjectSchema,
  updateProjectSchema,
  updateProjectStatusSchema,
  updateProjectCompletionSchema,
  updateProjectPrioritySchema,
  assignProjectSchema,
  bulkProjectOperationSchema,
  projectStatusValues,
  projectPriorityValues,
  projectStatusOptions,
  projectPriorityOptions,
  type CreateProjectInput,
  type UpdateProjectInput,
  type UpdateProjectStatusInput,
  type UpdateProjectCompletionInput,
  type UpdateProjectPriorityInput,
  type AssignProjectInput,
  type BulkProjectOperationInput,
  type ProjectStatus,
  type ProjectPriority,
  type CreateProjectFormInput,
  type UpdateProjectFormInput,
} from './project';

// Ticket schemas
export {
  createTicketSchema,
  updateTicketSchema,
  updateTicketStatusSchema,
  updateTicketPrioritySchema,
  assignTicketSchema,
  linkTicketToProjectSchema,
  updateTicketTagsSchema,
  logTicketTimeSchema,
  bulkTicketOperationSchema,
  listTicketsQuerySchema,
  ticketTypeValues,
  ticketStatusValues,
  ticketPriorityValues,
  ticketSourceValues,
  slaStatusValues,
  ticketTypeOptions,
  ticketStatusOptions,
  ticketPriorityOptions,
  ticketSourceOptions,
  slaStatusOptions,
  type CreateTicketInput,
  type UpdateTicketInput,
  type UpdateTicketStatusInput,
  type UpdateTicketPriorityInput,
  type AssignTicketInput,
  type LinkTicketToProjectInput,
  type UpdateTicketTagsInput,
  type LogTicketTimeInput,
  type BulkTicketOperationInput,
  type ListTicketsQuery,
  type TicketType,
  type TicketStatus,
  type TicketPriority,
  type TicketSource,
  type SlaStatus,
} from './ticket';

// Client schemas
export {
  createClientSchema,
  updateClientSchema,
  updateClientStatusSchema,
  bulkClientOperationSchema,
  listClientsQuerySchema,
  clientTypeValues,
  clientTypeOptions,
  type CreateClientInput,
  type UpdateClientInput,
  type UpdateClientStatusInput,
  type BulkClientOperationInput,
  type ListClientsQuery,
  type ClientType,
} from './client';
